FROM ubuntu:21.04
LABEL maintainer="yuriis@nvidia.com"
ENV DEBIAN_FRONTEND=noninteractive
# ENV http_proxy=http://10.210.9.1:3128/
# ENV https_proxy=http://10.210.9.1:3128/
RUN apt-get -q update && apt-get -y install python3-kubernetes && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
