apiVersion: v1
kind: Pod
metadata:
  name: test-py-k8s-pod
spec:
  serviceAccountName: demo-sa
  volumes:
  - name: work-data
    hostPath:
        path: /.autodirect/rdmzsysgwork/yuriis/k8s/il-blossom/
  containers:
  - name:  test-py-k8s-pod-1
    # image: harbor.mellanox.com/swx-storage/x86_64/python3-kubernetes:12.0
    image: harbor.mellanox.com/swx-storage/x86_64/py-k8s-scheduler:20210519
    imagePullPolicy: Always
    volumeMounts:
    - name: work-data
      mountPath: /work
    securityContext:
      privileged: false
    tty: true
  hostNetwork: false
  dnsPolicy: Default
  nodeSelector:
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
#    kubernetes.io/hostname: drock03
